const D=window.NATIVA_DATA||{};const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const CART='nativa-cart-v2',FAV='nativa-favs-v2',ORD='nativa-orders-v1',THEME='nativa-theme';const storageGet=k=>{try{return localStorage.getItem(k)}catch{return null}};const storageSet=(k,v)=>{try{localStorage.setItem(k,v);return true}catch{return false}};const read=(k,f)=>{try{const v=JSON.parse(storageGet(k));if(Array.isArray(f))return Array.isArray(v)?v:f;return v??f}catch{return f}};const write=(k,v)=>storageSet(k,JSON.stringify(v));const money=v=>'R$ '+Number(v||0).toFixed(2).replace('.',',');const cart=()=>read(CART,[]),favs=()=>read(FAV,[]);
function theme(v){const next=v==='dark'?'dark':'light';document.documentElement.dataset.theme=next;storageSet(THEME,next);$$('[data-theme-toggle]').forEach(b=>{b.textContent=next==='dark'?'☀':'☾';b.setAttribute('aria-label',next==='dark'?'Ativar modo claro':'Ativar modo escuro')})}
function shell(){const h=$('[data-shell-header]');if(h)h.innerHTML='<header class="topbar"><div class="wrap"><div class="toprow"><a class="brand" href="index.html">NATIVA</a><nav class="nav"><a href="catalogo.html">Loja</a><a href="manifesto.html">Materiais</a><a href="pedidos.html">Pedidos</a><a href="conta.html">Conta</a></nav><div class="actions"><button class="icon-btn" data-theme-toggle aria-label="Ativar modo escuro">☾</button><a class="icon-btn" href="favoritos.html">♡</a><button class="icon-btn" data-open-cart>🛒<span class="badge-count" data-cart-count>0</span></button></div></div><div class="searchbar"><label class="searchbox"><span>⌕</span><input data-search placeholder="Buscar produtos, materiais ou categorias"></label></div></div></header>';const f=$('[data-shell-footer]');if(f)f.innerHTML='<nav class="mobile-nav"><a href="index.html">⌂<span>Início</span></a><a href="catalogo.html">⌕<span>Loja</span></a><a href="pedidos.html">▤<span>Pedidos</span></a><a href="favoritos.html">♡<span>Favoritos</span></a></nav><footer class="app-footer"><div class="wrap footer-grid"><div><strong>NATIVA</strong><p>E-commerce conceitual de casa e bem-estar desenvolvido pela Alureal.</p></div><div><strong>Comprar</strong><p><a href="catalogo.html">Catálogo</a><br><a href="favoritos.html">Favoritos</a><br><a href="pedidos.html">Pedidos</a></p></div><div><strong>Marca</strong><p><a href="manifesto.html">Materiais</a><br><a href="conta.html">Conta</a></p></div></div></footer>';const d=$('[data-cart-shell]');if(d)d.innerHTML='<div class="scrim" data-scrim></div><aside class="drawer" data-drawer><div class="drawer-head"><h2>Carrinho</h2><button class="icon-btn" data-close-cart>×</button></div><div class="drawer-items" data-cart-items></div><div class="drawer-summary"><div class="summary-line"><span>Total</span><strong data-cart-total></strong></div><button class="primary" style="width:100%" onclick="location.href=\'checkout.html\'">Finalizar compra</button></div></aside>'}
function initTheme(){const raw=storageGet(THEME);const stored=raw==='dark'||raw==='light'?raw:null;let system='light';try{system=window.matchMedia?.('(prefers-color-scheme:dark)').matches?'dark':'light'}catch{}theme(stored||system);$$('[data-theme-toggle]').forEach(b=>b.onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark'))}
function productHref(id){const q=new URLSearchParams({id});if($('[data-catalog]')){const state=catalogQuery(catalogState).toString();if(state)q.set('catalog',state)}return 'produto.html?'+q.toString()}
function pById(id){return D.products.find(p=>p.id===id)}function card(p){const f=favs().includes(p.id);return '<article class="product" data-product="'+p.id+'" data-category="'+p.category+'"><div class="product-photo"><a href="'+productHref(p.id)+'"><img src="'+p.image+'" alt="'+p.name+'" loading="lazy"></a>'+(p.oldPrice?'<span class="sale">-'+Math.round((1-p.price/p.oldPrice)*100)+'%</span>':'')+'<button class="product-fav '+(f?'active':'')+'" data-fav="'+p.id+'">'+(f?'♥':'♡')+'</button></div><div class="product-body"><h3><a href="'+productHref(p.id)+'">'+p.name+'</a></h3><p>'+p.desc+'</p><div class="price-row"><div><span class="price">'+money(p.price)+'</span>'+(p.oldPrice?'<span class="old"> '+money(p.oldPrice)+'</span>':'')+'</div><button class="add" data-add="'+p.id+'">+</button></div></div></article>'}
function renderProducts(){$$('[data-products]').forEach(g=>{let list=D.products||[];if(g.dataset.products)list=list.filter(p=>p.category===g.dataset.products);g.innerHTML=list.map(card).join('')});bindProducts()}
function bindProducts(){$$('[data-add]').forEach(b=>b.onclick=e=>{e.preventDefault();const p=pById(b.dataset.add);const c=cart(),x=c.find(i=>i.id===p.id&&i.color===p.colors[0]&&i.size===p.sizes[0]);if(x)x.qty++;else c.push({id:p.id,qty:1,color:p.colors[0],size:p.sizes[0],unit:p.price});write(CART,c);renderCart();openCart()});$$('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();let f=favs(),id=b.dataset.fav;f=f.includes(id)?f.filter(x=>x!==id):[...f,id];write(FAV,f);renderProducts();renderCatalog();renderFavorites()})}
function renderCategories(){const g=$('[data-categories]');if(g)g.innerHTML=(D.categories||[]).map(c=>'<a class="category-card" href="catalogo.html?cat='+c.id+'"><img src="'+c.image+'" alt="'+c.name+'"><strong>'+c.name+'</strong></a>').join('')}
function renderReviews(){const g=$('[data-reviews]');if(g)g.innerHTML=(D.reviews||[]).map(r=>'<article class="review"><div class="stars">'+'★'.repeat(r.rating)+'</div><p>'+r.text+'</p><strong>'+r.name+'</strong><small> · '+r.product+'</small></article>').join('')}
// Only documented product materials are tagged; fragrance notes are not materials.
const catalogDefaults=()=>({cat:'',price:'',material:'',stock:'in',q:''});
function catalogFromQuery(query){
 const params=new URLSearchParams(query),state=catalogDefaults();
 const allowed={cat:(D.categories||[]).map(c=>c.id),price:['under100','100to300','over300'],material:['ceramica','algodao','madeira'],stock:['in','all']};
 for(const [key,values] of Object.entries(allowed)){if(values.includes(params.get(key)))state[key]=params.get(key)}
 state.q=(params.get('q')||'').slice(0,200);return state;
}
function catalogQuery(state){const params=new URLSearchParams(),defaults=catalogDefaults();for(const key of Object.keys(defaults)){if(state[key]!==defaults[key])params.set(key,state[key])}return params}
const normalizeSearch=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function catalogProducts(state){const q=normalizeSearch(state.q.trim());return (D.products||[]).filter(p=>
 (!state.cat||p.category===state.cat)&&
 (!state.price||(state.price==='under100'?p.price<=100:state.price==='100to300'?p.price>100&&p.price<=300:p.price>300))&&
 (!state.material||p.material===state.material)&&
 (state.stock==='all'||p.stock>0)&&
 (!q||normalizeSearch([p.name,p.desc,p.category,(D.categories||[]).find(c=>c.id===p.category)?.name||'',p.material||''].join(' ')).includes(q))
 )}
let catalogState=catalogFromQuery(location.search);
function renderCatalog(){
 const g=$('[data-catalog]');if(!g)return;
 const list=catalogProducts(catalogState);
 $$('[data-filter]').forEach(input=>input.value=catalogState[input.dataset.filter]);
 $$('[data-search]').forEach(input=>input.value=catalogState.q);
 g.innerHTML=list.length?list.map(card).join(''):'<p class="catalog-empty">Nenhum produto encontrado. Altere os filtros ou limpe a busca.</p>';
 $('[data-result-count]').textContent=list.length+' '+(list.length===1?'produto':'produtos');bindProducts();
}
function updateCatalog(next,replace=false){
 catalogState=next;const q=catalogQuery(next).toString();
 const url=location.pathname+(q?'?'+q:'')+location.hash;
 if(url!==location.pathname+location.search+location.hash)history[replace?'replaceState':'pushState'](null,'',url);
 renderCatalog();
}
function initCatalog(){
 if(!$('[data-catalog]'))return;
 $$('[data-filter]').forEach(input=>input.onchange=()=>updateCatalog({...catalogState,[input.dataset.filter]:input.value}));
 $('[data-clear-filters]').onclick=()=>updateCatalog(catalogDefaults());
 window.addEventListener('popstate',()=>{catalogState=catalogFromQuery(location.search);renderCatalog()});
 window.addEventListener('pageshow',()=>{catalogState=catalogFromQuery(location.search);renderCatalog()});
}
function initCatalogBack(){
 const back=$('[data-catalog-back]');if(!back)return;
 const raw=new URLSearchParams(location.search).get('catalog')||'';
 const query=catalogQuery(catalogFromQuery(raw)).toString();back.href='catalogo.html'+(query?'?'+query:'');
}
function renderDetail(){const r=$('[data-detail]');if(!r)return;const id=new URLSearchParams(location.search).get('id')||D.products[0].id,p=pById(id);document.title='NATIVA — '+p.name;r.innerHTML='<div class="detail-grid"><div class="detail-photo"><img src="'+p.image+'" alt="'+p.name+'"></div><div class="detail-info"><span class="eyebrow">'+p.category+'</span><h1>'+p.name+'</h1><div class="stars">★ '+p.rating+' · '+p.reviews+' avaliações</div><p>'+p.desc+'</p><h2>'+money(p.price)+'</h2><h3>Cor</h3><div class="option-row">'+p.colors.map((x,i)=>'<button class="option '+(i===0?'active':'')+'" data-color="'+x+'">'+x+'</button>').join('')+'</div><h3>Tamanho</h3><div class="option-row">'+p.sizes.map((x,i)=>'<button class="option '+(i===0?'active':'')+'" data-size="'+x+'">'+x+'</button>').join('')+'</div><p>Estoque: '+p.stock+' unidades</p><button class="primary" style="width:100%" data-detail-add>Adicionar ao carrinho</button></div></div>';let color=p.colors[0],size=p.sizes[0];$$('[data-color]',r).forEach(b=>b.onclick=()=>{$$('[data-color]',r).forEach(x=>x.classList.remove('active'));b.classList.add('active');color=b.dataset.color});$$('[data-size]',r).forEach(b=>b.onclick=()=>{$$('[data-size]',r).forEach(x=>x.classList.remove('active'));b.classList.add('active');size=b.dataset.size});$('[data-detail-add]',r).onclick=()=>{const c=cart();c.push({id:p.id,qty:1,color,size,unit:p.price});write(CART,c);renderCart();openCart()}}
function renderCart(){const c=cart();$$('[data-cart-count]').forEach(e=>e.textContent=c.reduce((n,i)=>n+i.qty,0));const total=c.reduce((s,i)=>s+i.unit*i.qty,0);$$('[data-cart-total]').forEach(e=>e.textContent=money(total));const g=$('[data-cart-items]');if(g)g.innerHTML=c.length?c.map((i,idx)=>{const p=pById(i.id);return '<article class="cart-item"><img src="'+p.image+'" alt=""><div><strong>'+p.name+'</strong><small>'+i.color+' · '+i.size+'</small><div class="qty"><button data-dec="'+idx+'">−</button><span>'+i.qty+'</span><button data-inc="'+idx+'">+</button></div></div><strong>'+money(i.unit*i.qty)+'</strong></article>'}).join(''):'<p>Seu carrinho está vazio.</p>';$$('[data-inc]').forEach(b=>b.onclick=()=>{const x=cart();x[+b.dataset.inc].qty++;write(CART,x);renderCart()});$$('[data-dec]').forEach(b=>b.onclick=()=>{const x=cart(),i=+b.dataset.dec;x[i].qty--;if(x[i].qty<=0)x.splice(i,1);write(CART,x);renderCart()})}
function openCart(){$('[data-drawer]')?.classList.add('open');$('[data-scrim]')?.classList.add('open')}function closeCart(){$('[data-drawer]')?.classList.remove('open');$('[data-scrim]')?.classList.remove('open')}function initCartShell(){$$('[data-open-cart]').forEach(b=>b.onclick=openCart);$$('[data-close-cart],[data-scrim]').forEach(b=>b.onclick=closeCart)}
function renderCartPage(){const g=$('[data-cart-page]');if(!g)return;const c=cart();g.innerHTML=c.length?c.map((i,idx)=>{const p=pById(i.id);return '<article class="cart-item"><img src="'+p.image+'" alt=""><div><strong>'+p.name+'</strong><small>'+i.color+' · '+i.size+'</small><div class="qty"><button data-dec="'+idx+'">−</button><span>'+i.qty+'</span><button data-inc="'+idx+'">+</button></div></div><strong>'+money(i.unit*i.qty)+'</strong></article>'}).join(''):'<p>Carrinho vazio.</p>';renderCart()}
function initCheckout(){const f=$('[data-checkout]');if(!f)return;f.onsubmit=e=>{e.preventDefault();const c=cart();if(!c.length){alert('Carrinho vazio.');return}const o={id:'NT'+Date.now().toString().slice(-6),date:new Date().toISOString(),items:c,total:c.reduce((s,i)=>s+i.unit*i.qty,0),status:'Pedido confirmado'};const arr=read(ORD,[]);arr.unshift(o);write(ORD,arr);write(CART,[]);location.href='pedidos.html'}}
function renderOrders(){const g=$('[data-orders]');if(g){const a=read(ORD,[]);g.innerHTML=a.length?a.map(o=>'<article class="order"><div><strong>Pedido #'+o.id+'</strong><p>'+o.items.map(i=>i.qty+'× '+pById(i.id).name).join(' · ')+'</p><small>'+new Date(o.date).toLocaleDateString('pt-BR')+' · '+money(o.total)+'</small></div><span>'+o.status+'</span></article>').join(''):'<p>Você ainda não tem pedidos.</p>'}}
function renderFavorites(){const g=$('[data-favorites]');if(g){const list=D.products.filter(p=>favs().includes(p.id));g.innerHTML=list.length?list.map(card).join(''):'<p>Nenhum favorito salvo.</p>';bindProducts()}}
function initSearch(){$$('[data-search]').forEach(input=>{input.maxLength=200;input.oninput=()=>{if($('[data-catalog]')){updateCatalog({...catalogState,q:input.value},true);return}const q=input.value.toLowerCase();$$('[data-product]').forEach(el=>{const p=pById(el.dataset.product);el.style.display=!q||[p.name,p.desc,p.category].join(' ').toLowerCase().includes(q)?'':'none'})}})}
const safeRun=(name,fn)=>{try{fn()}catch(error){console.error('[NATIVA] '+name+' failed',error)}};
function init(){safeRun('shell',shell);safeRun('theme',initTheme);safeRun('categories',renderCategories);safeRun('products',renderProducts);safeRun('reviews',renderReviews);safeRun('catalog',renderCatalog);safeRun('catalog-controls',initCatalog);safeRun('catalog-back',initCatalogBack);safeRun('detail',renderDetail);safeRun('cart',renderCart);safeRun('cart-page',renderCartPage);safeRun('orders',renderOrders);safeRun('favorites',renderFavorites);safeRun('cart-shell',initCartShell);safeRun('checkout',initCheckout);safeRun('search',initSearch)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();